version : '3'
services:
    mongodb:
        image: mongo
        container_name: my_first_mongodb
        ports:
            - "27017:27017"
    microservices:
        depends_on:
            - mongodb
        build: .
        ports:
            - "9012:9012"
        links:
                - "mongodb:database"
        volumes:
                - ".:/app"
